version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" 
  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"