version: "3.8"
services:
  node:
    container_name: react-app
    image: react-img
    build:
      context: .
    expose:
      - 8080
    ports:
      - 8080:8080
    command: [ "node", "index.js" ]